# type: ignore
"""not sure

Revision ID: f08284a0f616
Revises: 4d069caa36d9
Create Date: 2023-10-05 22:03:40.520919

"""

# revision identifiers, used by Alembic.
revision = "f08284a0f616"
down_revision = "4d069caa36d9"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
