# type: ignore
"""actual capture model defined

Revision ID: dacfb16c16be
Revises: cd74e328eaee
Create Date: 2023-10-05 19:16:56.854290

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "dacfb16c16be"
down_revision = "cd74e328eaee"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("captures", sa.Column("uuid", sa.Uuid(), nullable=False))
    op.add_column("captures", sa.Column("text", sa.String(length=200), nullable=False))
    op.add_column("captures", sa.Column("notes", sa.String(length=200), nullable=True))
    op.add_column(
        "captures",
        sa.Column("is_active", sa.Boolean(), default=True, nullable=True),
    )
    op.add_column(
        "captures",
        sa.Column("flagged", sa.Boolean(), default=False, nullable=True),
    )
    op.add_column(
        "captures",
        sa.Column("priority", sa.String(length=50), nullable=True),
    )
    op.add_column("captures", sa.Column("captured_time", sa.DateTime(), nullable=True))
    op.add_column("captures", sa.Column("happend_at", sa.DateTime(), nullable=True))
    op.add_column(
        "captures",
        sa.Column("captured_longitude", sa.Float(), nullable=True),
    )
    op.add_column("captures", sa.Column("captured_latitude", sa.Float(), nullable=True))
    op.add_column("captures", sa.Column("due_date", sa.DateTime(), nullable=True))
    op.alter_column(
        "captures",
        "created_at",
        existing_type=postgresql.TIMESTAMP(),
        nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "captures",
        "updated_at",
        existing_type=postgresql.TIMESTAMP(),
        nullable=False,
    )
    op.create_unique_constraint("uuid", "captures", ["uuid"])
    op.drop_column("captures", "name")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # )
    # op.drop_constraint(None, "captures", type_="unique")
    op.alter_column(
        "captures",
        "updated_at",
        existing_type=postgresql.TIMESTAMP(),
        nullable=True,
    )
    op.alter_column(
        "captures",
        "created_at",
        existing_type=postgresql.TIMESTAMP(),
        nullable=True,
        existing_server_default=sa.text("now()"),
    )
    op.drop_column("captures", "due_date")
    op.drop_column("captures", "captured_latitude")
    op.drop_column("captures", "captured_longitude")
    op.drop_column("captures", "happend_at")
    op.drop_column("captures", "captured_time")
    op.drop_column("captures", "priority")
    op.drop_column("captures", "flagged")
    op.drop_column("captures", "is_active")
    op.drop_column("captures", "notes")
    op.drop_column("captures", "text")
    op.drop_column("captures", "uuid")
    # ### end Alembic commands ###
