# type: ignore
"""empty message

Revision ID: c0d123a9bca3
Revises: 116d499d75ce
Create Date: 2023-10-04 16:50:06.317529

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "c0d123a9bca3"
down_revision = "116d499d75ce"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "bars",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column("genre", sa.String(), nullable=True),
        sa.Column("platform", sa.String(), nullable=True),
        sa.Column("price", sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "foos",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "bar_foos",
        sa.Column("bar_id", sa.Integer(), nullable=False),
        sa.Column("foo_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["bar_id"],
            ["bars.id"],
        ),
        sa.ForeignKeyConstraint(
            ["foo_id"],
            ["foos.id"],
        ),
        sa.PrimaryKeyConstraint("bar_id", "foo_id"),
    )
    op.create_table(
        "dazs",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("comment", sa.String(length=200), nullable=False),
        sa.Column("score", sa.Integer(), nullable=True),
        sa.Column("bar_id", sa.Integer(), nullable=True),
        sa.Column("foo_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["bar_id"],
            ["bars.id"],
        ),
        sa.ForeignKeyConstraint(
            ["foo_id"],
            ["foos.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("dazs")
    op.drop_table("bar_foos")
    op.drop_table("foos")
    op.drop_table("bars")
    # ### end Alembic commands ###
