"""captures users relationship

Revision ID: e3a46684f9f4
Revises: dacfb16c16be
Create Date: 2023-10-05 21:43:34.454890

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "e3a46684f9f4"
down_revision = "dacfb16c16be"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("captures", "is_active", existing_type=sa.BOOLEAN(), nullable=False)
    op.alter_column("captures", "flagged", existing_type=sa.BOOLEAN(), nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("captures", "flagged", existing_type=sa.BOOLEAN(), nullable=True)
    op.alter_column("captures", "is_active", existing_type=sa.BOOLEAN(), nullable=True)
    # ### end Alembic commands ###
