"""small change

Revision ID: 4d069caa36d9
Revises: e3a46684f9f4
Create Date: 2023-10-05 21:51:24.494835

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "4d069caa36d9"
down_revision = "e3a46684f9f4"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "captures",
        sa.Column("user_id", sa.UUID(), nullable=True),
    )
    op.create_foreign_key(None, "captures", "user", ["user_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_constraint(None, "captures", type_="foreignkey")
    op.drop_column("captures", "user_id")
    # ### end Alembic commands ###
