"""adding timestamp mixin

Revision ID: cd74e328eaee
Revises: ffc6fac79905
Create Date: 2023-10-05 18:36:12.598952

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "cd74e328eaee"
down_revision = "ffc6fac79905"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("bars", sa.Column("created_at", sa.DateTime(), nullable=False))
    op.add_column("bars", sa.Column("updated_at", sa.DateTime(), nullable=False))
    op.add_column("bars", sa.Column("deleted_at", sa.DateTime(), nullable=True))
    op.add_column("captures", sa.Column("deleted_at", sa.DateTime(), nullable=True))
    op.add_column("dazs", sa.Column("created_at", sa.DateTime(), nullable=False))
    op.add_column("dazs", sa.Column("updated_at", sa.DateTime(), nullable=False))
    op.add_column("dazs", sa.Column("deleted_at", sa.DateTime(), nullable=True))
    op.add_column("dummy_model", sa.Column("created_at", sa.DateTime(), nullable=False))
    op.add_column("dummy_model", sa.Column("updated_at", sa.DateTime(), nullable=False))
    op.add_column("dummy_model", sa.Column("deleted_at", sa.DateTime(), nullable=True))
    op.add_column("foos", sa.Column("deleted_at", sa.DateTime(), nullable=True))
    op.add_column("tags", sa.Column("created_at", sa.DateTime(), nullable=False))
    op.add_column("tags", sa.Column("updated_at", sa.DateTime(), nullable=False))
    op.add_column("tags", sa.Column("deleted_at", sa.DateTime(), nullable=True))
    op.add_column("user", sa.Column("created_at", sa.DateTime(), nullable=False))
    op.add_column("user", sa.Column("updated_at", sa.DateTime(), nullable=False))
    op.add_column("user", sa.Column("deleted_at", sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user", "deleted_at")
    op.drop_column("user", "updated_at")
    op.drop_column("user", "created_at")
    op.drop_column("tags", "deleted_at")
    op.drop_column("tags", "updated_at")
    op.drop_column("tags", "created_at")
    op.drop_column("foos", "deleted_at")
    op.drop_column("dummy_model", "deleted_at")
    op.drop_column("dummy_model", "updated_at")
    op.drop_column("dummy_model", "created_at")
    op.drop_column("dazs", "deleted_at")
    op.drop_column("dazs", "updated_at")
    op.drop_column("dazs", "created_at")
    op.drop_column("captures", "deleted_at")
    op.drop_column("bars", "deleted_at")
    op.drop_column("bars", "updated_at")
    op.drop_column("bars", "created_at")
    # ### end Alembic commands ###
